stages:
  get_data:
    cmd: python -m src.data.get_data
    deps:
    - src/data/get_data.py
    outs:
    - datasets/raw_data/DL Dataset/test.txt
    - datasets/raw_data/DL Dataset/train.txt
    - datasets/raw_data/DL Dataset/val.txt
  data_prep:
    cmd: python -m src.data.data_prep
    deps:
    - src/data/data_prep.py
    - datasets/raw_data/DL Dataset/test.txt
    - datasets/raw_data/DL Dataset/train.txt
    - datasets/raw_data/DL Dataset/val.txt
    params:
    - dataset_dir
    outs:
    - datasets/processed_data/ds_train.joblib
    - datasets/processed_data/ds_val.joblib
    - datasets/processed_data/ds_test.joblib
    - datasets/processed_data/char_index.joblib
  train:
    cmd: python src/models/train.py
    deps:
    - src/models/train.py
    - src/models/model.py
    - datasets/processed_data/ds_train.joblib
    - datasets/processed_data/ds_val.joblib
    - datasets/processed_data/char_index.joblib
    - params.yaml
    params:
    - dataset_dir
    - loss_function
    - optimizer
    - batch_train
    - epoch
    - categories
    outs:
    - datasets/metrics/phishing_model.h5
  predict:
    cmd: python src/models/predict.py
    deps:
    - src/models/predict.py
    - datasets/processed_data/ds_test.joblib
    - datasets/metrics/phishing_model.h5
    outs:
    - datasets/metrics/predictions.joblib
  evaluate:
    cmd: python src/models/evaluate.py
    deps:
    - src/models/evaluate.py
    - datasets/metrics/predictions.joblib
    outs:
    - datasets/metrics/statistics.json
  release:
    cmd: python src/release.py
    deps:
    - datasets/processed_data/char_index.joblib
    - datasets/metrics/phishing_model.h5
    params:
    - version
metrics:
- datasets/metrics/metrics.json
- datasets/metrics/metrics.json
- datasets/metrics/metrics.json
- datasets/metrics/metrics.json
- datasets/metrics/metrics.json
plots:
- datasets/metrics/plots/metrics:
    x: step
- datasets/metrics/plots/metrics:
    x: step
- datasets/metrics/plots/metrics:
    x: step
- datasets/metrics/plots/metrics:
    x: step
- datasets/metrics/plots/metrics:
    x: step
artifacts:
  phishing_model:
    path: datasets/metrics/phishing_model.h5
    type: model
