stages:
  get_data:
    cmd: python src/get_data.py
    deps:
    - src/get_data.py
    outs:
    - datasets/raw_data/DL Dataset/test.txt
    - datasets/raw_data/DL Dataset/train.txt
    - datasets/raw_data/DL Dataset/val.txt
  data_prep:
    cmd: python src/data_prep.py
    deps:
    - src/data_prep.py
    - datasets/raw_data/DL Dataset/test.txt
    - datasets/raw_data/DL Dataset/train.txt
    - datasets/raw_data/DL Dataset/val.txt
    params:
    - dataset_dir
    outs:
    - datasets/processed_data/ds_train.joblib
    - datasets/processed_data/ds_val.joblib
    - datasets/processed_data/ds_test.joblib
    - datasets/processed_data/char_index.joblib
  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - src/model.py
    - datasets/processed_data/ds_train.joblib
    - datasets/processed_data/ds_val.joblib
    - datasets/processed_data/char_index.joblib
    - params.yaml
    params:
    - dataset_dir
    - loss_function
    - optimizer
    - batch_train
    - epoch
    - categories
    outs:
    - datasets/metrics/phishing_model.h5
  predict:
    cmd: src/predict.py
    deps:
    - src/model/predict.py
    - data/processed/x_data.joblib
    - data/processed/y_data.joblib
    - src/model/trained_model.h5
    outs:
    - data/processed/report.joblib
  evaluate:
    cmd: python src/model/evaluate.py
    deps:
    - src/model/evaluate.py
    - data/processed/report.joblib
    outs:
    - reports/metrics.json

metrics:
- reports/metrics.json
- datasets/metrics/metrics.json
plots:
- datasets/metrics/plots/metrics:
    x: step
