'loss_function': 'binary_crossentropy'
'optimizer': 'adam'
'sequence_length': 200
'batch_train': 1000
'batch_test': 1000
'categories': ['phishing', 'legitimate']
'char_index': None
'epoch': 1
'embedding_dimension': 50
'dataset_dir': "datasets/"