name: ML Model Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Cache Poetry dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pypoetry
          ~/.virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: ${{ runner.os }}-poetry-

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Install dependencies
      run: |
        poetry install

    - name: Download and process data
      run: |
        poetry run python -m src.data.get_data
        poetry run python -m src.data.data_prep

    - name: Train model
      run: |
        poetry run python -m src.models.train

    - name: Run tests with coverage
      run: |
        poetry run pytest --cov=src --cov-report=xml tests/
      continue-on-error: true

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: reports/

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.xml

    - name: Notify on failure
      if: failure()
      run: |
        # Add notification commands here, e.g., sending an email or Slack message
        echo "Tests failed. Sending notification."
