name: ML Model Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install poetry
      run: |
        pip install poetry
        poetry install
        poetry run pip install dvc

#    - name: Download data and process data
#      run: |
#         poetry run python -m src.data.get_data
#         poetry run python -m src.data.data_prep

    - name: Pull model with DVC
      run: |
        dvc pull

    - name: Run tests
      run: |
        poetry run pytest tests/staleness_test.py
        poetry run pytest tests/feature_test.py
        poetry run pytest tests/non_determinism.py
        poetry run pytest tests/data_slices_test.py
        poetry run pytest tests/intergration_test.py
        poetry run pytest tests/mutamorphic_test.py