name: Release
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      TAG: ''
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Retrieve tag
        run: |
          TAG=$(grep 'version' params.yaml | awk '{print $2}')
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Create release
        id: create_release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: v${TAG}
          release_name: Release v${TAG}
      - name: Upload Joblib File
        uses: actions/upload-artifact@v2
        with:
          name: release.joblib
          path: release.joblib